/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.one;

import org.junit.Test;

public class FirstTest {

    @Test
    public void testAppHasAGreeting() {
        new First().one();
    }
}
